import { useEffect, useState } from "react";
import { ArrowRight, ChevronLeft, ChevronRight, Dumbbell, ListChecks, ShieldCheck, Sparkles, Timer, Utensils, Zap } from "lucide-react";
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/")({ component: IronCoreSalesPage });

const story = ["Tudo começa com uma inquietação.","Sempre acreditei que grandes transformações começam quando surge uma vontade real de mudar e descobrir até onde podemos chegar.","O esporte sempre esteve presente na minha vida, mas foi na musculação que encontrei algo diferente. Quanto mais eu treinava, mais queria entender por que algumas pessoas evoluíam tanto enquanto outras passavam anos se esforçando sem alcançar os resultados que buscavam.","Foi essa busca que me levou a estudar Educação Física.","Com o tempo, percebi que treinamento era apenas uma parte da transformação. Passei a estudar também nutrição, estratégia e tudo aquilo que poderia transformar esforço em resultado.","E então percebi algo que me marcou:","a maioria das pessoas não desiste porque não quer mudar. Elas desistem porque não sabem exatamente como mudar.","Foi nesse momento que nasceu uma ideia.","Reunir conhecimento, profissionais e estratégias em um só lugar, tornando acessível aquilo que muitas vezes depende de personal, experiência ou anos de tentativa e erro.","Foi assim que começou a nascer a Iron Core.","Não como mais um programa de treino, mas como um caminho claro para quem quer transformar o próprio corpo e não sabe por onde começar.","Porque, no fim, talvez o que separa você do físico que deseja não seja falta de esforço.","Talvez seja apenas nunca ter tido a direção certa."];

function QuizAndOffer(){return null;}

function IronCoreSalesPage(){
 const cards=[[Dumbbell,"Treino específico para você"],[Utensils,"Treine de forma rápida"],[Zap,"Treino que cabe na sua rotina"],[ShieldCheck,"Garantia de 1 semana"]] as const;
 const [testimonialIndex,setTestimonialIndex]=useState(0); const testimonials=["Antes e depois","Mensagem real 01","Mensagem real 02","Mensagem real 03"];
 return <main className="min-h-screen bg-[#050505] text-white">
  <style>{`#impactamos > div > h2{text-align:center!important;margin-left:auto!important;margin-right:auto!important}#impactamos .impact-card h3{font-size:clamp(.72rem,1.4vw,.9rem)!important;line-height:1.15!important;letter-spacing:.08em!important}#impactamos .impact-card p{font-size:.68rem!important;line-height:1.45!important}`}</style>
  <nav className="fixed left-0 right-0 top-0 z-50 border-b border-white/10 bg-[#050505]/80 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 sm:px-8"><span className="text-sm font-black tracking-[.3em]">IRON CORE</span><a href="#como-funciona" className="text-xs font-bold uppercase tracking-[.2em] text-white/45 hover:text-[#d9ff00]">Como funciona</a></div></nav>
  <section className="relative min-h-screen overflow-hidden pt-16"><div className="absolute inset-0 bg-black"/><div className="relative mx-auto flex min-h-[calc(100vh-64px)] max-w-7xl items-center justify-center px-5 py-12"><div className="relative z-10 mx-auto w-full max-w-5xl text-center"><p className="mb-6 text-[10px] font-black uppercase tracking-[.4em] text-[#d9ff00]">IRON CORE • PROTOCOLO DE EVOLUÇÃO</p><h1 className="max-w-4xl text-5xl font-black uppercase leading-[.88] tracking-[-.045em] sm:text-7xl lg:text-[6.5rem]">DO ZERO AO<br/><span className="text-[#d9ff00]">SHAPE DE PRAIA</span></h1><p className="mt-7 text-xl font-semibold text-white/70 sm:text-2xl">sem depender de personal.</p><p className="mx-auto mt-5 max-w-xl text-sm leading-7 text-white/40">Treinamento pensado para a sua realidade, com direção profissional e uma estratégia que cabe na sua rotina.</p><a href="#impactamos" className="mx-auto mt-9 inline-flex items-center gap-3 rounded-xl bg-[#d9ff00] px-7 py-4 text-xs font-black uppercase tracking-[.14em] text-black">Conhecer a Iron Core <ArrowRight size={17}/></a></div></div></section>
  <section id="impactamos" className="border-t border-white/10 bg-[#080808] py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8"><h2 className="mt-4 text-4xl font-black uppercase leading-none sm:text-6xl">O QUE IMPACTAMOS<br/><span className="text-white/35">NA SUA VIDA</span></h2><div className="mt-16 grid gap-4 md:grid-cols-2">{cards.map(([,title],i)=><article key={title} className="impact-card rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="mb-5 flex h-12 w-12 items-center justify-center rounded-xl border border-white/15 bg-white/[.03] text-white">{i===0?<Dumbbell size={23}/>:i===1?<Timer size={23}/>:i===2?<Zap size={23}/>:<ShieldCheck size={23}/>}</div><h3 className="font-black uppercase">{title}</h3></article>)}</div></div></section>
  <section id="como-funciona" className="py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8"><h2 className="text-4xl font-black uppercase leading-none sm:text-6xl">COMO FUNCIONA A <span className="text-[#d9ff00]">IRON CORE?</span></h2></div></section>
  <section className="border-y border-white/10 bg-[#080808] py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8"><h2 className="text-4xl font-black uppercase leading-none sm:text-6xl">ANTES X DEPOIS<br/><span className="text-white/35">E MENSAGENS REAIS</span></h2><div className="mt-12 overflow-hidden"><div className="flex gap-4" style={{transform:`translateX(-${testimonialIndex*25}%)`}}>{testimonials.map((item,i)=><article key={i} className="min-w-[78%] sm:min-w-[42%] lg:min-w-[31%]"><div className="flex aspect-[4/5] items-center justify-center rounded-2xl border border-dashed border-white/15 bg-white/[.02] p-6 text-center"><Sparkles size={42} className="text-white/10"/><p className="ml-4 text-[10px] font-black uppercase tracking-[.25em] text-[#d9ff00]">{item}</p></div></article>)}</div></div><div className="mt-6 flex justify-between"><div className="flex gap-2">{testimonials.map((_,i)=><button key={i} onClick={()=>setTestimonialIndex(i)} className={"h-1.5 rounded-full "+(i===testimonialIndex?"w-8 bg-[#d9ff00]":"w-2 bg-white/20")}/>)}</div><div className="flex gap-2"><button onClick={()=>setTestimonialIndex(v=>Math.max(0,v-1))} className="rounded-full border border-white/10 p-2"><ChevronLeft size={17}/></button><button onClick={()=>setTestimonialIndex(v=>Math.min(testimonials.length-1,v+1))} className="rounded-full border border-white/10 p-2"><ChevronRight size={17}/></button></div></div></div></section>
  <section className="py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8"><h2 className="text-4xl font-black uppercase leading-none sm:text-6xl">A HISTÓRIA<br/><span className="text-[#d9ff00]">POR TRÁS</span></h2><article className="mt-10 text-sm leading-7 text-white/60">{story.map((p,i)=><p key={i} className="mb-5">{p}</p>)}</article></div></section>
  <footer className="border-t border-white/10 py-10"><div className="mx-auto max-w-7xl px-5 text-center text-[10px] font-black uppercase tracking-[.25em] text-white/25">IRON CORE • Direção certa. Execução consistente. Evolução.</div></footer>
 </main>;
}
